// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMu3pL-Be12BCaDPuGWCPdg7eRGG9624',
    appId: '1:725803610254:web:f3f43638e8202dca8919df',
    messagingSenderId: '725803610254',
    projectId: 'aomlah-1d151',
    authDomain: 'aomlah-1d151.firebaseapp.com',
    storageBucket: 'aomlah-1d151.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVbpQo5o00ZHYuHLE_Wybrf4tjmAfnWw',
    appId: '1:725803610254:android:07dc9dc8f93db1e68919df',
    messagingSenderId: '725803610254',
    projectId: 'aomlah-1d151',
    storageBucket: 'aomlah-1d151.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA00jD2fHTcw53dnVWivs468sp9WRNetfg',
    appId: '1:725803610254:ios:5afc4581513d5bcb8919df',
    messagingSenderId: '725803610254',
    projectId: 'aomlah-1d151',
    storageBucket: 'aomlah-1d151.appspot.com',
    iosClientId: '725803610254-0245cg91ptamdgfeonrugad7kr17tkfb.apps.googleusercontent.com',
    iosBundleId: 'com.aomlah.app',
  );
}
